import { DateTime } from "luxon";

import { BaseModel } from "@adonisjs/lucid/orm";

import { typedColumn } from "#decorators/typed_model";

export default class CalendarEvent extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer" })
  declare id: number;

  @typedColumn({ type: "string", optional: true })
  declare googleCalId: string | null;

  get isGoogleEvent(): boolean {
    return this.googleCalId !== null;
  }

  @typedColumn.dateTime({
    autoCreate: false,
    autoUpdate: false,
    autoGenerated: false,
  })
  declare startTime: DateTime;

  @typedColumn.dateTime({
    autoCreate: false,
    autoUpdate: false,
    autoGenerated: false,
  })
  declare endTime: DateTime;

  @typedColumn({ type: "string" })
  declare location: string;

  @typedColumn({ type: "string" })
  declare name: string;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
}
