import vine from "@vinejs/vine";
import { DateTime } from "luxon";

import { BaseModel, belongsTo } from "@adonisjs/lucid/orm";
import type { BelongsTo } from "@adonisjs/lucid/types/relations";

import { typedColumn } from "#decorators/typed_model";
import DasTimetable from "#models/das_timetable";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export default class DasTimetableEntry extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: true })
  declare id: number;

  @typedColumn({ isPrimary: true, foreignKeyOf: () => DasTimetable })
  declare timetableId: number;

  @belongsTo(() => DasTimetable, {
    foreignKey: "timetableId",
    localKey: "id",
  })
  declare timetable: BelongsTo<typeof DasTimetable>;

  @typedColumn({ type: "string" })
  declare name: string;

  @typedColumn.dateTime({ optional: true })
  declare startTime: DateTime;

  @typedColumn.dateTime({
    optional: true,
    validator: vine.date().after("startTime").nullable(),
  })
  declare endTime: DateTime;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
