import { DateTime } from "luxon";

import { BaseModel, belongsTo } from "@adonisjs/lucid/orm";
import type { BelongsTo } from "@adonisjs/lucid/types/relations";

import { typedColumn } from "#decorators/typed_model";
import FileEntry from "#models/file_entry";
import StudentOrganization from "#models/student_organization";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export default class DasOrganization extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: true })
  declare id: number;

  @typedColumn({ type: "string" })
  declare name: string;

  @typedColumn({ type: "string", optional: true })
  declare description: string | null;

  @typedColumn({
    foreignKeyOf: () => FileEntry,
    optional: true,
  })
  declare logoKey: string | null;

  @typedColumn({
    foreignKeyOf: () => StudentOrganization,
    optional: true,
  })
  declare studentOrganizationId: number | null;

  @belongsTo(() => StudentOrganization, {
    localKey: "id",
    foreignKey: "studentOrganizationId",
  })
  declare studentOrganization: BelongsTo<typeof StudentOrganization>;

  @belongsTo(() => FileEntry, {
    localKey: "id",
    foreignKey: "logoKey",
  })
  declare logo: BelongsTo<typeof FileEntry>;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
