import vine from "@vinejs/vine";
import { DateTime } from "luxon";

import { BaseModel, belongsTo } from "@adonisjs/lucid/orm";
import type { BelongsTo } from "@adonisjs/lucid/types/relations";

import { typedColumn } from "#decorators/typed_model";
import Das from "#models/das";
import StudentOrganization from "#models/student_organization";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

import FileEntry from "./file_entry.js";

export default class DasStand extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: true })
  declare id: number;

  @typedColumn({ type: "string", validator: vine.string().maxLength(7) })
  declare number: string; // Knowing PWr, stand number could not be a number

  @typedColumn({ isPrimary: true, foreignKeyOf: () => Das })
  declare dasId: number;

  @belongsTo(() => Das, {
    localKey: "id",
    foreignKey: "dasId",
  })
  declare das: BelongsTo<typeof Das>;

  @typedColumn({ type: "string", validator: vine.string().maxLength(127) })
  declare name: string;

  @typedColumn({
    type: "string",
    optional: true,
    validator: vine.string().maxLength(7).optional().nullable(),
  })
  declare floor: string | null; // Also knowing PWr, floor number could also not be a number

  @typedColumn({
    type: "string",
    optional: true,
  })
  declare description: string | null;

  @typedColumn({
    isPrimary: true,
    foreignKeyOf: () => StudentOrganization,
    optional: true,
  })
  declare studentOrganizationId: number | null;

  @typedColumn({ foreignKeyOf: () => FileEntry, optional: true })
  declare logoKey: string | null;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  @belongsTo(() => StudentOrganization, {
    localKey: "id",
    foreignKey: "studentOrganizationId",
  })
  declare studentOrganization: BelongsTo<typeof StudentOrganization>;

  @belongsTo(() => FileEntry, {
    localKey: "id",
    foreignKey: "logoKey",
  })
  declare logo: BelongsTo<typeof FileEntry>;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
