import vine from "@vinejs/vine";
import { DateTime } from "luxon";

import { BaseModel, belongsTo } from "@adonisjs/lucid/orm";
import type { BelongsTo } from "@adonisjs/lucid/types/relations";

import { typedColumn } from "#decorators/typed_model";
import Das from "#models/das";
import DasOrganization from "#models/das_organization";
import Floor from "#models/floor";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

import FileEntry from "./file_entry.js";

export default class DasStand extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: true })
  declare id: number;

  @typedColumn({ type: "string", validator: vine.string().maxLength(7) })
  declare number: string; // Knowing PWr, stand number could not be a number

  @typedColumn({ foreignKeyOf: () => Das })
  declare dasId: number;

  @belongsTo(() => Das, {
    localKey: "id",
    foreignKey: "dasId",
  })
  declare das: BelongsTo<typeof Das>;

  @typedColumn({ type: "string", validator: vine.string().maxLength(127) })
  declare name: string;

  @typedColumn({ foreignKeyOf: () => Floor, optional: true })
  declare floorId: number | null;

  @belongsTo(() => Floor, {
    localKey: "id",
    foreignKey: "floorId",
  })
  declare floor: BelongsTo<typeof Floor>;

  @typedColumn({
    type: "string",
    optional: true,
  })
  declare description: string | null;

  @typedColumn({ foreignKeyOf: () => DasOrganization, optional: true })
  declare dasOrganizationId: number | null;

  @belongsTo(() => DasOrganization, {
    localKey: "id",
    foreignKey: "dasOrganizationId",
  })
  declare dasOrganization: BelongsTo<typeof DasOrganization>;

  @typedColumn({ foreignKeyOf: () => FileEntry, optional: true })
  declare logoKey: string | null;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  @belongsTo(() => FileEntry, {
    localKey: "id",
    foreignKey: "logoKey",
  })
  declare logo: BelongsTo<typeof FileEntry>;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
