import vine from "@vinejs/vine";
import { DateTime } from "luxon";

import { BaseModel, computed } from "@adonisjs/lucid/orm";

import { typedColumn } from "#decorators/typed_model";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export default class MobileConfig extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer" })
  declare id: number;

  @typedColumn({ type: "integer", autoGenerated: true })
  declare cmsReferenceNumber: number;

  @typedColumn({ type: "integer", autoGenerated: true })
  declare translatorReferenceNumber: number;

  @typedColumn({
    type: "integer",
    validator: vine.number().withoutDecimals().min(1),
  })
  declare daySwapLookahead: number;

  /**
   * @deprecated Since issue #217. Use cmsReferenceNumber instead
   */
  @computed()
  get referenceNumber() {
    return this.cmsReferenceNumber;
  }

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  public static async bumpCmsCache() {
    await MobileConfig.query().increment("cms_reference_number", 1);
  }

  public static async bumpTranslatorCache() {
    await MobileConfig.query().increment("translator_reference_number", 1);
  }

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
