import { DateTime } from "luxon";

import { BaseModel } from "@adonisjs/lucid/orm";

import { typedColumn } from "#decorators/typed_model";

// TODO: change the name to something simpler and handle it in the admin panel
export default class StudentOrganizationsStudentOrganizationTag extends BaseModel {
  public static table = "student_organizations_student_organization_tags";

  @typedColumn({ isPrimary: true, type: "string", autoGenerated: false })
  declare tag: string;

  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: false })
  declare studentOrganizationId: number;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;
}
