import { BaseModel } from "@adonisjs/lucid/orm";

import { typedColumn } from "#decorators/typed_model";

export default class OrganizationTagPivot extends BaseModel {
  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: false })
  declare id: number;

  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: false })
  declare tag: string;
}
