import { DateTime } from "luxon";

import { BaseModel } from "@adonisjs/lucid/orm";
import type { ManyToMany } from "@adonisjs/lucid/types/relations";

import { typedColumn, typedManyToMany } from "#decorators/typed_model";
import FirebaseTopic from "#models/firebase_topic";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export default class PushNotificationEntry extends BaseModel {
  public static table = "push_notification_entries";

  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: true })
  declare id: number;

  @typedColumn({ type: "string" })
  declare title: string;

  @typedColumn({ type: "string" })
  declare body: string;

  @typedColumn({ type: "json", optional: true })
  declare data: Record<string, string> | null;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedManyToMany(() => FirebaseTopic, {
    pivotTable: "push_notifications_topics",
    localKey: "id",
    pivotColumns: {},
    pivotForeignKey: "id",
    pivotRelatedForeignKey: "firebase_topic_topic_name",
    pivotTimestamps: false,
  })
  declare topics: ManyToMany<typeof FirebaseTopic>;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
