import { DateTime } from "luxon";

import { BaseModel } from "@adonisjs/lucid/orm";
import type { ManyToMany } from "@adonisjs/lucid/types/relations";

import { typedColumn, typedManyToMany } from "#decorators/typed_model";
import FirebaseTopic from "#models/firebase_topic";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export interface PushNotificationData {
  title: string;
  body: string;
  data: Record<string, string> | undefined;
}

export default class PushNotificationEntry extends BaseModel {
  public static fromData(
    data: PushNotificationData,
    wasSent: boolean,
  ): PushNotificationEntry {
    const entry = new PushNotificationEntry();
    entry.title = data.title;
    entry.body = data.body;
    entry.wasSent = wasSent;
    entry.data = data.data ?? null;
    return entry;
  }

  @typedColumn({ isPrimary: true, type: "integer", autoGenerated: true })
  declare id: number;

  @typedColumn({ type: "string" })
  declare title: string;

  @typedColumn({ type: "string" })
  declare body: string;

  @typedColumn({ type: "json", optional: true })
  declare data: Record<string, string> | null;

  @typedColumn({ type: "boolean" })
  declare wasSent: boolean;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedManyToMany(() => FirebaseTopic, {
    pivotTable: "push_notification_entries_topics",
    localKey: "id",
    relatedKey: "topicName",
    pivotForeignKey: "push_notification_entry_id",
    pivotRelatedForeignKey: "firebase_topic_topic_name",
    pivotTimestamps: false,
    pivotColumns: {},
  })
  declare topics: ManyToMany<typeof FirebaseTopic>;

  public static async getByTopic(
    include?: string[],
    exclude?: string[],
  ): Promise<PushNotificationEntry[]> {
    let query = PushNotificationEntry.query();
    if (include !== undefined && include.length > 0) {
      query = query.whereHas("topics", (topicsQuery) =>
        topicsQuery.whereIn("topic_name", include),
      );
    }

    if (exclude !== undefined && exclude.length > 0) {
      query = query.whereDoesntHave("topics", (topicsQuery) =>
        topicsQuery.whereIn("topic_name", exclude),
      );
    }
    return query;
  }

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
