import vine from "@vinejs/vine";
import { DateTime } from "luxon";

import { BaseModel } from "@adonisjs/lucid/orm";

import { typedColumn } from "#decorators/typed_model";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export default class SksOpeningHours extends BaseModel {
  public static table = "sks_opening_hours";

  @typedColumn({
    isPrimary: true,
    type: "string",
    autoGenerated: false,
    validator: vine.string().toLowerCase().minLength(2),
  })
  declare language: string;

  @typedColumn({ type: "string" })
  declare canteen: string;

  @typedColumn({ type: "string" })
  declare cafe: string;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
