import { DateTime } from "luxon";

import { BaseModel } from "@adonisjs/lucid/orm";
import type { ManyToMany } from "@adonisjs/lucid/types/relations";

import { typedColumn, typedManyToMany } from "#decorators/typed_model";
import StudentOrganization from "#models/student_organization";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

export default class StudentOrganizationTag extends BaseModel {
  public static selfAssignPrimaryKey = true;

  @typedColumn({ isPrimary: true, type: "string", autoGenerated: false })
  declare tag: string;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  @typedManyToMany(() => StudentOrganization, {
    pivotTable: "student_organizations_student_organization_tags",
    localKey: "tag",
    pivotForeignKey: "tag",
    pivotRelatedForeignKey: "student_organization_id",
    pivotTimestamps: true,
    pivotColumns: {},
  })
  declare organizations: ManyToMany<typeof StudentOrganization>;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
