import { MorphMap } from "@holoyan/adonisjs-permissions";
import {
  AclModelInterface,
  ModelIdType,
} from "@holoyan/adonisjs-permissions/types";
import { DateTime } from "luxon";

import { BaseModel, belongsTo } from "@adonisjs/lucid/orm";
import type { BelongsTo } from "@adonisjs/lucid/types/relations";

import { typedColumn } from "#decorators/typed_model";
import { Branch } from "#enums/branch";
import { OrganizationSource } from "#enums/organization_source";
import { OrganizationStatus } from "#enums/organization_status";
import { OrganizationType } from "#enums/organization_type";
import Department from "#models/department";
import StudentOrganization from "#models/student_organization";
import { preloadRelations } from "#scopes/preload_helper";
import { handleSearchQuery } from "#scopes/search_helper";
import { handleSortQuery } from "#scopes/sort_helper";

import FileEntry from "./file_entry.js";
import User from "./user.js";

@MorphMap("student_organization_drafts")
export default class StudentOrganizationDraft
  extends BaseModel
  implements AclModelInterface
{
  getModelId(): ModelIdType {
    return this.id;
  }
  @typedColumn({ isPrimary: true, type: "integer" })
  declare id: number;

  @typedColumn({ type: "string" })
  declare name: string;

  @typedColumn({ type: "boolean" })
  declare isStrategic: boolean;

  @typedColumn({ type: Branch })
  declare branch: Branch;

  @typedColumn({ foreignKeyOf: () => Department, optional: true })
  declare departmentId: number | null;

  @typedColumn({ foreignKeyOf: () => FileEntry, optional: true })
  declare logoKey: string | null;

  @typedColumn({ foreignKeyOf: () => FileEntry, optional: true })
  declare coverKey: string | null;

  @typedColumn({ type: "string", optional: true })
  declare description: string | null;

  @typedColumn({ type: "string", optional: true })
  declare shortDescription: string | null;

  @typedColumn({ type: "boolean" })
  declare coverPreview: boolean;

  @typedColumn({ type: OrganizationSource })
  declare source: OrganizationSource;

  @typedColumn({ type: OrganizationType })
  declare organizationType: OrganizationType;

  @typedColumn({ type: OrganizationStatus })
  declare organizationStatus: OrganizationStatus;

  // Link to original published organization (optional)
  @typedColumn({ foreignKeyOf: () => StudentOrganization, optional: true })
  declare originalId: number | null;

  // Track who created this draft (set automatically by the controller)
  @typedColumn({ foreignKeyOf: () => User, autoGenerated: true })
  declare createdByUserId: number;

  @belongsTo(() => Department)
  declare department: BelongsTo<typeof Department>;

  @belongsTo(() => FileEntry, { localKey: "id", foreignKey: "logoKey" })
  declare logo: BelongsTo<typeof FileEntry>;

  @belongsTo(() => FileEntry, { localKey: "id", foreignKey: "coverKey" })
  declare cover: BelongsTo<typeof FileEntry>;

  @typedColumn({ type: "string", optional: true })
  declare enName: string;

  @typedColumn({ type: "string", optional: true })
  declare enDescription: string;

  @typedColumn({ type: "string", optional: true })
  declare enShortDescription: string;

  @belongsTo(() => StudentOrganization, {
    localKey: "id",
    foreignKey: "originalId",
  })
  declare original: BelongsTo<typeof StudentOrganization>;

  @belongsTo(() => User, {
    localKey: "id",
    foreignKey: "createdByUserId",
  })
  declare createdBy: BelongsTo<typeof User>;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  static preloadRelations = preloadRelations();
  static handleSearchQuery = handleSearchQuery();
  static handleSortQuery = handleSortQuery();
}
