import { DateTime } from "luxon";

import { BaseModel, manyToMany } from "@adonisjs/lucid/orm";
import type { ManyToMany } from "@adonisjs/lucid/types/relations";

import { typedColumn } from "#decorators/typed_model";
import StudentOrganization from "#models/student_organization";

export default class StudentOrganizationTag extends BaseModel {
  @typedColumn({ isPrimary: true, type: "string", autoGenerated: false })
  declare tag: string;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime;

  @manyToMany(() => StudentOrganization, {
    pivotTable: "student_organizations_student_organization_tags",
    localKey: "tag",
    pivotForeignKey: "tag",
    pivotRelatedForeignKey: "student_organization_id",
    pivotTimestamps: true,
  })
  declare organizations: ManyToMany<typeof StudentOrganization>;

  public static getStudentOrganizationRelationKey() {
    return "tag";
  }
}
