import { MorphMap, hasPermissions } from "@holoyan/adonisjs-permissions";
import {
  AclModelInterface,
  ModelIdType,
} from "@holoyan/adonisjs-permissions/types";
import vine from "@vinejs/vine";
import { DateTime } from "luxon";

import { DbAccessTokensProvider } from "@adonisjs/auth/access_tokens";
import { withAuthFinder } from "@adonisjs/auth/mixins/lucid";
import { compose } from "@adonisjs/core/helpers";
import hash from "@adonisjs/core/services/hash";
import logger from "@adonisjs/core/services/logger";
import { BaseModel, beforeSave, scope } from "@adonisjs/lucid/orm";

import { typedColumn } from "#decorators/typed_model";
import { sha256 } from "#utils/hash";

const AuthFinder = withAuthFinder(() => hash.use("scrypt"), {
  uids: ["email"],
  passwordColumnName: "password",
});

@MorphMap("users")
export default class User
  extends compose(BaseModel, AuthFinder, hasPermissions())
  implements AclModelInterface
{
  getModelId(): ModelIdType {
    return this.id;
  }

  @typedColumn({ isPrimary: true, type: "integer" })
  declare id: number;

  @typedColumn({ type: "string", optional: true })
  declare fullName: string | null;

  @typedColumn({ type: "string", validator: vine.string().email() })
  declare email: string;

  @typedColumn({ type: "string", autoGenerated: true, serializeAs: null })
  declare password: string;

  @typedColumn({
    type: "string",
    autoGenerated: true,
    optional: true,
    serializeAs: null,
  })
  declare resetPasswordToken: string | null;

  @typedColumn.dateTime({ serializeAs: null })
  declare resetPasswordTokenExpiration: DateTime | null;

  @typedColumn.dateTime({ autoCreate: true })
  declare createdAt: DateTime;

  @typedColumn.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null;

  static accessTokens = DbAccessTokensProvider.forModel(User);

  @beforeSave()
  static async hashToken(user: User) {
    if (
      user.$dirty.resetPasswordToken !== undefined &&
      user.resetPasswordToken !== null
    ) {
      // deterministic hash for easier lookup
      user.resetPasswordToken = sha256(user.resetPasswordToken);
    }
  }

  static compareTokens = scope((query, token: string) => {
    void query.where("reset_password_token", sha256(token));
  });

  get hasValidResetToken() {
    return (
      this.resetPasswordTokenExpiration !== null &&
      this.resetPasswordTokenExpiration.diffNow().milliseconds > 0
    );
  }

  /**
   * Updates the user's password, invalidates any existing reset tokens and saves the model
   *
   * @param password new password
   */
  async updatePassword(password: string, options?: { reset: boolean }) {
    this.password = password;
    if (options?.reset ?? false) {
      this.clearResetToken();
    }
    await this.save();
    logger.info(`Password changed for user ${this.email}`);
  }

  /**
   * Invalidates any existing reset tokens and saves the model
   */
  clearResetToken() {
    this.resetPasswordToken = null;
    this.resetPasswordTokenExpiration = null;
  }

  /**
   * Generates random secure token for password reseting and stores it in database
   * Hashing before storing should be handled by `beforeSave()` hook in lucid
   * Note: saves the model
   *
   * @param expirationDate time till the token is valid. Pass DateTime instance using e.g. `DateTime.now().plus({minutes: 15})`
   * @returns generated token (not hashed)
   */
  async generateResetPasswordToken(
    expirationDate: DateTime<true>,
  ): Promise<string> {
    const token = crypto.randomUUID().toString();
    this.resetPasswordToken = token;
    this.resetPasswordTokenExpiration = expirationDate;
    await this.save();
    return token;
  }
}
