export enum LinkType {
  Default = 'default',
  Facebook = 'facebook',
  Instagram = 'instagram',
  LinkedIn = 'linkedin',
  Mail = 'mailto:',
  YouTube = 'youtu',
  GitHub = 'github',
  TopwrBuildings = 'topwr:buildings',
  Phone = 'tel',
  X = 'https://x.com',
  TikTok = 'tiktok',
  Discord = 'discord',
  Twitch = 'twitch',
}
