name: Docker images

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Attempt to build the image
        run: docker build .
