name: Docker

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.after || github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
          fetch-depth: 0

      - name: Attempt to build the image
        run: docker build .
