name: Link reminder

on:
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  check_issue_link:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
      - name: Wait
        run: sleep 5

      - name: Check linking
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const prBody = context.payload.pull_request.body || "";
            const issueLinkRegex = /(?:fix(?:e[sd])?|close(?:[sd])?|resolve(?:[sd])?):?\s+#\d+/i;
            if(!issueLinkRegex.test(prBody)){
              await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: "Pull request does not have an issue linked to it. Please link it."
                });
            }
