name: ESLint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      TZ: UTC
      PORT: 3333
      HOST: localhost
      LOG_LEVEL: info
      APP_KEY: really-hard-key-to-guess-so-please-dont-do-it
      NODE_ENV: development
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: echo "make sure that you always have the latest version of package.json pushed to the repository, cause `npm ci` will install the exact versions of the dependencies that are in package-lock.json" && npm ci

      - name: Run Lint
        run: npm run lint

      - name: Check types
        run: npm run typecheck

      - name: Run tests
        run: NODE_ENV="test" npm run test

      - name: Run prettier
        run: npm run prettiercheck
