name: Pull request automation

on:
  pull_request_target:
    type: opened

permissions:
  pull-requests: write

jobs:
  assign_to_author:
    name: Assign author if no assignee set
    if: ${{ github.event.pull_request.assignee == null }}
    runs-on: ubuntu-latest
    env:
      PR_NUM: ${{ github.event.pull_request.number }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Assign the author to the pull request
        run: |
          curl -LvX POST --fail-with-body \
            -H "Authorization: Bearer $GH_TOKEN" \
            --json '{"assignees": ["'"$PR_AUTHOR"'"]}' \
            "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/$PR_NUM/assignees"
